const products = [
  {
    name: 'Esgarraet',
    categoryId: '1',
    price: 4.5,
    ingredients: '',
    allergy: ['4'],
    order: '0',
  },
  {
    name: 'Ensaladilla rusa',
    categoryId: '1',
    price: 4.25,
    ingredients: '',
    allergy: ['1', '3', '4', '6', '12'],
    order: '1',
  },
  {
    name: 'Calamares andaluza',
    categoryId: '1',
    price: 6,
    ingredients: '',
    allergy: ['1', '2'],
    order: '2',
  },
  {
    name: 'Choricitos a la sidra',
    categoryId: '1',
    price: 4.25,
    ingredients: '',
    allergy: ['7'],
    order: '3',
  },
  {
    name: 'Patatas bravas',
    categoryId: '1',
    price: 4,
    ingredients: '',
    allergy: ['3', '7', '6'],
    order: '4',
  },
  {
    name: 'Morro de cerdo',
    categoryId: '1',
    price: 4.5,
    ingredients: '',
    allergy: ['4'],
    order: '5',
  },
  {
    name: 'Sepia plancha',
    categoryId: '1',
    price: 7.5,
    ingredients: '',
    allergy: ['4'],
    order: '6',
  },
  {
    name: 'Croquetón',
    categoryId: '1',
    price: 1.2,
    ingredients: 'Jamón, Pollo, Boletus',
    allergy: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '12', '13'],
    order: '7',
  },
  {
    name: 'Chipirones a la andaluza',
    categoryId: '1',
    price: 6,
    ingredients: '',
    allergy: ['1', '4'],
    order: '8',
  },
  {
    name: 'Pincho moruno',
    categoryId: '1',
    price: 2.5,
    ingredients: '',
    allergy: [],
    order: '9',
  },
  {
    name: 'Revuelto de ajetes trigueros y gambas',
    categoryId: '1',
    price: 4.25,
    ingredients: '',
    allergy: ['2', '3'],
    order: '10',
  },
  {
    name: 'Tabla de embutidos a la plancha de cebolla caramelizada, boletus y barbacoa',
    categoryId: '1',
    price: 5.5,
    ingredients: '',
    allergy: ['7'],
    order: '11',
  },
  {
    name: 'Gambas al ajillo',
    categoryId: '1',
    price: 7.5,
    ingredients: '',
    allergy: ['2'],
    order: '12',
  },
  {
    name: 'Ensalada de manzana con foie',
    categoryId: '2',
    price: 8,
    ingredients: 'Baby leaf, tomate, cebolleta, manzana caramelizada, foie y tostas de pan',
    allergy: ['1', '3', '7', '10'],
    order: '1',
  },
  {
    name: 'Ensalada de pollo con vinagreta',
    categoryId: '2',
    price: 8,
    ingredients: 'Baby leaf, tomate, huevo, cebolla tierna, pollo y nueces',
    allergy: ['1', '3', '7', '8'],
    order: '2',
  },
  {
    name: 'Ensalada con pera y queso de cabra',
    categoryId: '2',
    price: 8,
    ingredients: 'Baby leaf, tomate, cebolla, huevo, queso de cabra, aceite de membrillo, frutos secos y pera',
    allergy: ['3', '5', '7', '8', '9'],
    order: '3',
  },
  {
    name: 'Ensalada de tomate con atún y cebolleta',
    categoryId: '2',
    price: 5.5,
    ingredients: 'Tomate, atún, cebolleta y aceitunas',
    allergy: ['3', '4', '12'],
    order: '4',
  },
  {
    name: 'Codillo asado',
    categoryId: '3',
    price: 12.5,
    ingredients: '',
    allergy: [],
    order: '1',
  },
  {
    name: 'Entrecot al grill',
    categoryId: '3',
    price: 14,
    ingredients: '',
    allergy: [],
    order: '2',
  },
  {
    name: 'Bistec de ternera con patatas y verduras',
    categoryId: '3',
    price: 7,
    ingredients: '',
    allergy: [],
    order: '3',
  },
  {
    name: 'Solomillo de cerdo a la pimienta',
    categoryId: '3',
    price: 12,
    ingredients: '',
    allergy: ['1', '2', '3', '4', '6', '7', '9'],
    order: '4',
  },
  {
    name: 'Lomo de cerdo con patatas y huevo frito',
    categoryId: '3',
    price: 6,
    ingredients: '',
    allergy: ['3'],
    order: '5',
  },
  {
    name: 'Pechuga de pollo con patatas y ensalada',
    categoryId: '3',
    price: 6,
    ingredients: '',
    allergy: ['10'],
    order: '6',
  },
  {
    name: 'Pinchos morunos con huevo y patatas',
    categoryId: '3',
    price: 6.5,
    ingredients: '',
    allergy: ['3'],
    order: '7',
  },
  {
    name: 'Sepionet a la plancha',
    categoryId: '3',
    price: 11.5,
    ingredients: '',
    allergy: ['4'],
    order: '8',
  },
  {
    name: 'Merluza fresca a la plancha',
    categoryId: '3',
    price: 10.5,
    ingredients: '',
    allergy: ['4'],
    order: '9',
  },
  {
    name: 'Emperador a la plancha',
    categoryId: '3',
    price: 11.5,
    ingredients: '',
    allergy: ['4'],
    order: '10',
  },
  {
    name: 'Salmon a la plancha',
    categoryId: '3',
    price: 11.5,
    ingredients: '',
    allergy: ['3'],
    order: '11',
  },
  {
    name: 'Panacota de café',
    categoryId: '4',
    price: 3.5,
    ingredients: '',
    allergy: ['7'],
    order: '1',
  },
  {
    name: 'Tarta de chocolate',
    categoryId: '4',
    price: 3.75,
    ingredients: '',
    allergy: ['1', '7', '8'],
    order: '2',
  },
  {
    name: 'Tarta de queso',
    categoryId: '4',
    price: 3.75,
    ingredients: '',
    allergy: ['1', '7'],
    order: '3',
  },
  {
    name: 'Tarta de capuccino',
    categoryId: '4',
    price: 4,
    ingredients: '',
    allergy: ['1', '3', '7', '8'],
    order: '4',
  },
  {
    name: 'Suflé de chocolate con helado',
    categoryId: '4',
    price: 4,
    ingredients: '',
    allergy: ['1', '7', '8'],
    order: '5',
  },
  {
    name: 'Torrija caramelizada con helado',
    categoryId: '4',
    price: 4.5,
    ingredients: '',
    allergy: ['1', '3', '6', '7'],
    order: '6',
  },
  {
    name: 'Copa de helado',
    categoryId: '4',
    price: 3.5,
    ingredients: '',
    allergy: ['1', '7'],
    order: '7',
  },
  {
    name: 'Cornete de helado',
    categoryId: '4',
    price: 1.8,
    ingredients: '',
    allergy: ['1', '7'],
    order: '8',
  },
  {
    name: 'Refrescos',
    categoryId: '4',
    price: 1.6,
    ingredients: '',
    allergy: [],
    order: '1',
  },
  {
    name: 'Agua 0,5L',
    categoryId: '8',
    price: 1.1,
    ingredients: '',
    allergy: [],
    order: '1',
  },
  {
    name: 'Tercio San Miguel',
    categoryId: '8',
    price: 1.5,
    ingredients: '',
    allergy: [],
    order: '1',
  },
  {
    name: 'Tercio clara San Miguel',
    categoryId: '8',
    price: 1.8,
    ingredients: '',
    allergy: [],
    order: '1',
  },
  {
    name: 'Tercio 0/0 San Miguel',
    categoryId: '8',
    price: 1.8,
    ingredients: '',
    allergy: [],
    order: '1',
  },
  {
    name: 'Tercio sin gluten San Miguel',
    categoryId: '8',
    price: 1.6,
    ingredients: '',
    allergy: [],
    order: '1',
  },
  {
    name: 'Doble Selecta',
    categoryId: '8',
    price: 1.7,
    ingredients: '',
    allergy: [],
    order: '1',
  },
  {
    name: 'Doble Warsteiner',
    categoryId: '8',
    price: 2,
    ingredients: '',
    allergy: [],
    order: '1',
  },
  {
    name: 'Jarra de Selecta 1,5L',
    categoryId: '8',
    price: 8,
    ingredients: '',
    allergy: [],
    order: '1',
  },
  {
    name: 'Jarra de Warsteiner 1,5L',
    categoryId: '8',
    price: 9.5,
    ingredients: '',
    allergy: [],
    order: '1',
  },
  {
    name: 'Copa de vino tinto',
    categoryId: '8',
    price: 2,
    ingredients: '',
    allergy: [],
    order: '1',
  },
  {
    name: 'Copa de vino blanco',
    categoryId: '8',
    price: 2.5,
    ingredients: '',
    allergy: [],
    order: '1',
  },
  {
    name: 'Viña mayor (roble)',
    categoryId: '9',
    price: 13,
    ingredients: 'Vino tinto',
    allergy: [],
    order: '1',
  },
  {
    name: 'Viña mayor (crianza)',
    categoryId: '9',
    price: 18,
    ingredients: 'Vino tinto',
    allergy: [],
    order: '1',
  },
  {
    name: 'Glorioso (Rioja)',
    categoryId: '9',
    price: 11.5,
    ingredients: 'Vino tinto',
    allergy: [],
    order: '1',
  },
  {
    name: 'Glorioso (100 aniversario)',
    categoryId: '9',
    price: 19.5,
    ingredients: 'Vino tinto',
    allergy: [],
    order: '1',
  },
  {
    name: 'Celeste (Ribera del Duero)',
    categoryId: '9',
    price: 15,
    ingredients: 'Vino tinto',
    allergy: [],
    order: '1',
  },
  {
    name: 'Lambrusco (Espumoso)',
    categoryId: '9',
    price: 8,
    ingredients: 'Vino tinto',
    allergy: [],
    order: '1',
  },
  {
    name: 'Juan de Juanes (Valenciano)',
    categoryId: '9',
    price: 8,
    ingredients: 'Vino tinto',
    allergy: [],
    order: '1',
  },
  {
    name: 'Marqués de Riscal',
    categoryId: '9',
    price: 25.5,
    ingredients: 'Vino tinto',
    allergy: [],
    order: '1',
  },
  {
    name: 'Viña mayor (Verdejo)',
    categoryId: '9',
    price: 10.5,
    ingredients: 'Vino blanco',
    allergy: [],
    order: '1',
  },
  {
    name: 'Gran Pescador (Espumoso)',
    categoryId: '9',
    price: 11,
    ingredients: 'Vino blanco',
    allergy: [],
    order: '1',
  },
  {
    name: 'Pazo de bruxa (Albariño)',
    categoryId: '9',
    price: 16.5,
    ingredients: 'Vino blanco',
    allergy: [],
    order: '1',
  },
  {
    name: 'Peñascal (Espumoso)',
    categoryId: '9',
    price: 7,
    ingredients: 'Vino rosado',
    allergy: [],
    order: '1',
  },
  {
    name: 'Carta (Bodega torres)',
    categoryId: '9',
    price: 8,
    ingredients: 'Vino rosado',
    allergy: [],
    order: '1',
  },
  {
    name: 'Mixto',
    categoryId: '7',
    price: 2.75,
    ingredients: 'Jamon york y queso',
    allergy: ['1', '7'],
    order: '1',
  },
  {
    name: 'Mixto con huevo',
    categoryId: '7',
    price: 3.5,
    ingredients: 'Jamon yor, queso y huevo',
    allergy: ['1', '3', '7'],
    order: '1',
  },
  {
    name: 'Vegetal con atún',
    categoryId: '7',
    price: 4.25,
    ingredients: 'Baby leaf, tomate, atún, huevo, esparragos y mayonesa',
    allergy: ['1', '3', '4'],
    order: '1',
  },
  {
    name: 'Fresquito',
    categoryId: '7',
    price: 4.25,
    ingredients: 'Guacamole, rucula, tomate, jamón york y queso fresco',
    allergy: ['1', '7'],
    order: '1',
  },
  {
    name: 'Pollo',
    categoryId: '7',
    price: 4.25,
    ingredients: 'Baby leaf, tomate, queso, pechuga de pollo y salsa césar',
    allergy: ['1', '3', '7'],
    order: '1',
  },
  {
    name: 'Chivito con huevo',
    categoryId: '5',
    price: 5,
    ingredients: 'Baby leaf, tomate, lomo, bacon, huevo y mayonesa',
    allergy: ['1', '3', '6'],
    order: '1',
  },
  {
    name: 'Brascada de ternera',
    categoryId: '5',
    price: 6,
    ingredients: 'Bistec de ternera, jamón y cebolla',
    allergy: ['1'],
    order: '1',
  },
  {
    name: 'Almussafes',
    categoryId: '5',
    price: 4.75,
    ingredients: 'Sobrasada, bacon, queso y cebolla',
    allergy: ['1', '6', '7'],
    order: '1',
  },
  {
    name: 'Chupadedos',
    categoryId: '5',
    price: 4.75,
    ingredients: 'Bacon, queso y huevos',
    allergy: ['1', '3', '6'],
    order: '1',
  },
  {
    name: 'Vegetal con pollo',
    categoryId: '5',
    price: 4.25,
    ingredients: 'Baby leaf, tomate, pechuga de pollo y mayonesa',
    allergy: ['1', '3'],
    order: '1',
  },
  {
    name: 'Pollo con queso azul',
    categoryId: '5',
    price: 5.75,
    ingredients: 'Pechuga de pollo, bacon y crema de queso azul',
    allergy: ['1', '7', '12'],
    order: '1',
  },
  {
    name: 'Ternera',
    categoryId: '5',
    price: 5,
    ingredients: 'Bistec de ternera, pimientos y cebolla caramelizada',
    allergy: ['1'],
    order: '1',
  },
  {
    name: 'Cántabro',
    categoryId: '5',
    price: 4.5,
    ingredients: 'Tomate, atún, anchoas y aceitunas',
    allergy: ['1', '4'],
    order: '1',
  },
  {
    name: 'Llauraor',
    categoryId: '5',
    price: 4.5,
    ingredients: 'Tortilla francesa, jamón serrano y tomate',
    allergy: ['1', '3'],
    order: '1',
  },
  {
    name: 'Sepia',
    categoryId: '5',
    price: 7.5,
    ingredients: 'Sepia plancha y salsa mery',
    allergy: ['1', '4'],
    order: '1',
  },
  {
    name: 'Pollo con cammembert',
    categoryId: '5',
    price: 5.5,
    ingredients: 'Rúcula tomate pollo y camembert',
    allergy: ['1', '7'],
    order: '1',
  },
  {
    name: 'Patriota',
    categoryId: '5',
    price: 4.5,
    ingredients: 'Tortilla de patatas, bacon y ajo-aceite',
    allergy: ['1', '3', '6'],
    order: '1',
  },
  {
    name: 'Calamares',
    categoryId: '5',
    price: 6,
    ingredients: 'Calamares y mayonesa',
    allergy: ['1', '2'],
    order: '1',
  },
  {
    name: 'Lomo con foie',
    categoryId: '5',
    price: 6,
    ingredients: 'Lomo, foie, rucula y cebolla',
    allergy: ['1', '3', '7'],
    order: '1',
  },
  {
    name: 'Serranito de pollo',
    categoryId: '5',
    price: 5,
    ingredients: 'Pechuga de pollo plancha, jamón serrano y cebolla caramelizada',
    allergy: ['1'],
    order: '1',
  },
  {
    name: 'Cammembert',
    categoryId: '5',
    price: 5.5,
    ingredients: 'Rúcula, queso camembert y bacon',
    allergy: ['1', '7'],
    order: '1',
  },
  {
    name: 'Solomillo',
    categoryId: '5',
    price: 6.5,
    ingredients: 'Solomillo de cerdo, bacon y parmesano',
    allergy: ['1', '7'],
    order: '1',
  },
  {
    name: 'Hamburguesa completa',
    categoryId: '6',
    price: 6,
    ingredients: 'Burguer de vaca, baby leaf, tomate, cebolla, bacon, queso y huevo',
    allergy: ['1','3','6','7','12'],
    order: '1',
  },
  {
    name: 'Hamburguesa con queso azul',
    categoryId: '6',
    price: 5.5,
    ingredients: 'Burguer, crema de queso azul, baby leaf, tomate y cebolla crujiente',
    allergy: ['1','6','7','12'],
    order: '1',
  },
  {
    name: 'Hamburguesa Oklahoma',
    categoryId: '6',
    price: 5,
    ingredients: 'Burguer sabor barbacoa, lechuga, queso y cebolla',
    allergy: ['1','6','7','12'],
    order: '1',
  },
  {
    name: 'Hamburguesa con foie',
    categoryId: '6',
    price: 6,
    ingredients: 'Burguer de vaca, foie, baby leaf, queso de cabra y cebolla caramelizada',
    allergy: ['1','12'],
    order: '1',
  },
  {
    name: 'Hamburguesa serrana',
    categoryId: '6',
    price: 6,
    ingredients: 'Burguer de vaca, baby leaf, tomate, jamón serrano y queso semicurado',
    allergy: ['1','6','7','12'],
    order: '1',
  },
  {
    name: 'Hamburguesa rústica',
    categoryId: '6',
    price: 6,
    ingredients: 'Burguer de vaca, rúcula, tomate, parmesano y cebolla',
    allergy: ['1','6','7','12'],
    order: '1',
  },
  {
    name: 'Hamburguesa de boletus',
    categoryId: '6',
    price: 5.50,
    ingredients: 'Burguer de boletus, baby leaf, tomate, bacon y cebolla',
    allergy: ['1','6','7','12'],
    order: '1',
  },
  {
    name: 'Hamburguesa de la casa',
    categoryId: '6',
    price: 6,
    ingredients: 'Burguer con bacon, morcilla, pimiento verde, baby leaf y tomate',
    allergy: ['1','6','7','12'],
    order: '1',
  },
  {
    name: 'Hamburguesa campera',
    categoryId: '6',
    price: 6.5,
    ingredients: 'Burguer, jamón serrano, ajos tiernos, huevo, baby leaf y tomate',
    allergy: ['1','3','6','7','12'],
    order: '1',
  },
]

const getAll = () => {
  return Promise.resolve(products)
}

const getAllByCategoryId = id => {
  const filteredProducts = products.filter(product => product.categoryId === id)
  return Promise.resolve(filteredProducts)
}

export const ProductClient = {
  getAll,
  getAllByCategoryId,
}
